.TH PSPS 1

.SH NAME
pspm \- Packet Synchronization Protocol Slave

.SH SYNOPSIS
.B psps
[\fIOPTIONS\fR]

.SH DESCRIPTION
.B psps
implements the slave role of the Packet Synchronization Protocol.

.SH OPTIONS
\fB General options\fR
.RS

.TP
.BR \-h
Displays the help message.

.TP
.BR \-l
Sets the log file. If this option is set all program output will be
recorded in the log file independently from the verbosity level specified
with the '\-v' option.

.TP
.BR \-v \fInum\fR
Sets the program output verbosity level as follow:
.RS
.IP \fB0\fP
error
.IP \fB1\fP
warning
.IP \fB2\fP
information
.IP \fB3\fP
debug
.IP
.RE

.RE

\fB Action options\fR
.RS

.BR \-c
Performs calibration and writes channel latency statistics in the file specified with the '-u' option

.BR \-c
Performs synchronization reading channel latency statistics in the file specified with the '-u' option

.RE

\fB Options valid for calibration only\fR
.RS

.BR \-d \fInum\fR
Sets the lenght in samples of the drift evaluation window and enables drift evaluation during calibration.

.RE

\fB Options valid for both synchronization and calibration\fR
.RS

.BR \-n \fInum\fR
Sets the number of timestamp packets to reveive before stopping (default value: infinite). This option is mandatory if synchronization.
action is selected.

.BR \-u \fIfilename\fR
Sets the filename of the statistics file. This file is written during calibration and read during synchronization (mandatory option).

.BR \-p \fIport\fR
Sets the PSP slave UDP port (default value: 4242).

.BR \-c
Avoids the computation of latency percentiles during calibration and synchronization, saving memory and CPU load. If this option
is specified, the only valid synchronization algorithm is 'mean'.

.RE

\fB Options valid for synchronization only\fR
.RS

.BR \-v \fInum\fR
Sets the syncronization algorithm as follow:
.RS
.IP \fB0\fP
mean
.IP \fB1\fP
10th percentile
.IP \fB2\fP
25th percentile
.IP \fB3\fP
median (default algorithm)
.IP
.RE

.BR \-w \fInum\fR
Sets the size of observation window in number of received timestamp (default value: 100)

.BR \-f
Simulates synchronization (avoids adjustments of machine clock)

.RE

\fB Secure mode options\fR
.RS

.BR \-k \fIfilename\fR
Sets the filename of the cryptographic key for secure protocol mode. The key shall be a 32 byte binary file. This option also
enables the secure protocol mode.

.RE

\fB Debugging options\fR
.RS

.BR \-t \fIfilename\fR
If set, the measured latency samples are written in text format to \fBfilename\fR.

.BR \-r \fIfilename\fR
If set, the clock corrections are written in text format to \fBfilename\fR.

.RE

\fB Tweaking options\fR
.RS

.BR \-o \fInum\fR
Set a static offset which is applied to latency measurement.

.BR \-i \fInum\fR
Compensate the clocks drift by \fBnum\fR ppb for calibration.

.RE

.SH EXIT STATUS
Zero if OK, non-zero if error encountered.

.SH EXAMPLE
Starting PSP slave for calibration:
.RS
\fBpspm -c -ustats.txt -n10000 -d100\fR
.RE
Starting PSP slave for synchronization:
.RS
\fBpspm -s -ustats.txt\fR
.RE

.SH AUTHOR
Written by Alpha Catharsis (\fBalpha.catharsis@gmail.com\fR).

.SH REPORTING BUGS
Please raise issues at \fBhttps://github.com/alpha-catharsis/psp/issues\fR.

